// Command pinhash emits the expected-hash registry for a freshly built
// env-guard interposer: `go run ./internal/envguard/cmd/pinhash <lib> >
// internal/envguard/hashes_generated.go`. Invoked by `make envguard` so the
// shipped binary and its pinned hash are produced in one step — a library
// built by any other route has no pin and is refused at load.
package main

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: pinhash <library>")
		os.Exit(2)
	}
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, "pinhash: read:", err)
		os.Exit(1)
	}
	sum := sha256.Sum256(raw)
	fmt.Println("// Code generated by make envguard. DO NOT EDIT.")
	fmt.Println("// Pins the interposer built alongside this binary. Merged into")
	fmt.Println("// pinnedHashes at init; absent file = empty map = guard refused.")
	fmt.Println()
	fmt.Println("package envguard")
	fmt.Println()
	fmt.Println("var generatedPins = map[string]string{")
	fmt.Printf("\t%q: %q,\n", filepath.Base(os.Args[1]), fmt.Sprintf("%x", sum))
	fmt.Println("}")
	fmt.Println()
	fmt.Println("func init() {")
	fmt.Println("\tfor k, v := range generatedPins {")
	fmt.Println("\t\tpinnedHashes[k] = v")
	fmt.Println("\t}")
	fmt.Println("}")
}
